services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    networks:
      - backbone
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1g

  url-shortener:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - backbone
    deploy:
      resources:
        limits:
          cpus: '3.0'
          memory: 5g

networks:
  backbone: 
    